name: go2-convex-mpc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy[version='<2']
  - pinocchio
  - matplotlib[version='>=3.7,<3.9']
  - scipy
  - libgcc-ng
  - libstdcxx-ng
  - casadi
  - myst-parser
  - cmake
  - pkg-config
  - boost-cpp
  - ninja
  - eigenpy
  - eigen
  - assimp
  - console_bridge
  - urdfdom_headers
  - tinyxml2
  - urdfdom
  - hpp-fcl

  - pip
  - pip:
      - mujoco==3.1.6
      - -e .


